# Музыка
define music_main_theme = "audio/bg/foot290_02-iliaque-singularite.mp3"
define music_experimental_android_work_06 = "audio/bg/foot280_02-ish10_yow1r0-experimental_android_work_06.mp3"
define music_overthrive_uncharted_realms = "audio/bg/foot291_05-overthrive-uncharted_realms.mp3"
define music_ashes = "audio/bg/foot284_04-deep_intruder-ashes.mp3"
define music_p5 = "audio/bg/foot167_06-zmg-p5.mp3"
define music_23_peak = "audio/bg/foot037_01-qx55-23_peak.mp3"
define music_casasoso = "audio/bg/foot037_08-qx55-casasoso.mp3"
define music_atmosphere = "audio/bg/foot040_01-wshgaukd-atmosphere.mp3"
define music_after_all = "audio/bg/foot037_11-qx55-after_all.mp3"
define music_after_all_7 = "audio/bg/foot076_08-qx55-after_all.mp3"
define music_yes_you_are_made_in_japan = "audio/bg/foot038_09-qx55-yes_you_are_made_in_japan.mp3"
define music_maestro = "audio/bg/foot269_02-ollie_cram-maestro.mp3"
define music_verse = "audio/bg/foot269_03-ollie_cram-verse.mp3"
define music_travel_in_peace = "audio/bg/foot076_05-qx55-travel_in_peace.mp3"
define music_monochrome = "audio/bg/bump218_04-hzk-monochrome.mp3"

# Игра
define sfx_door_knocks_modern = "audio/sfx/door-knocks-modern.ogg"
define sfx_door_opening = "audio/sfx/door-opening.ogg"
define sfx_fast_steps = "audio/sfx/fast_steps.ogg"
define sfx_footsteps = "audio/sfx/footsteps.ogg"
define sfx_glass_smash_5 = "audio/sfx/glass-smash-5.ogg"
define sfx_gynation_paper_medium_3 = "audio/sfx/gynation__paper-medium-3.ogg"
define sfx_hit_knock = "audio/sfx/hit_knock.ogg"
define sfx_hit_swing_sword = "audio/sfx/hit-swing-sword.ogg"
define sfx_hit_wooden = "audio/sfx/hit-wooden.ogg"
define sfx_metal_gate_squeak_01 = "audio/sfx/metal_gate_squeak_01.ogg"
define sfx_metal_door_groaning = "audio/sfx/metal-door-groaning.ogg"
define sfx_metall_hitmouv_short = "audio/sfx/metall_hitmouv_short.ogg"
define sfx_radio_bar_switch = "audio/sfx/radio-bar-switch.ogg"
define sfx_rage_door_knock = "audio/sfx/rage_door-knock.ogg"
define sfx_rat_squeak = "audio/sfx/RAT_squeak.ogg"
define sfx_rat_tiny_insectrat_1_3_pitches = "audio/sfx/RAT_tiny-insectrat-1-3-pitches.ogg"
define sfx_running_wood = "audio/sfx/running_wood.ogg"
define sfx_running_on_stairs = "audio/sfx/running-on-stairs.ogg"
define sfx_rustle = "audio/sfx/rustle.ogg"
define sfx_shelk_knock = "audio/sfx/shelk_knock.ogg"
define sfx_shorokh = "audio/sfx/shorokh.ogg"
define sfx_shorokh_gromko2 = "audio/sfx/shorokh_gromko2.ogg"
define sfx_skrip = "audio/sfx/skrip.ogg"
define sfx_slow_walking_leaves = "audio/sfx/slow-walking-leaves.ogg"
define sfx_squeaking_in_wind3 = "audio/sfx/squeaking-in-wind3.ogg"
define sfx_stepping_on_broken_glass = "audio/sfx/stepping-on-broken-glass.ogg"
define sfx_steps_defolt = "audio/sfx/steps_defolt.ogg"
define sfx_steps_on_concrete = "audio/sfx/steps-on-concrete.ogg"
define sfx_stremniy_shelest = "audio/sfx/stremniy_shelest.ogg"
define sfx_sword_swing = "audio/sfx/sword-swing.ogg"
define sfx_udar = "audio/sfx/udar.ogg"
define sfx_white_noise_10s = "audio/sfx/white_noise-10s.ogg"
define sfx_white_noise_build_shoroh = "audio/sfx/white-noise-build-shoroh.ogg"
define sfx_white_noise_defolt = "audio/sfx/white-noise-defolt.ogg"
define sfx_white_noise_reverse = "audio/sfx/white-noise-reverse.ogg"
define sfx_whitenoiserhythm = "audio/sfx/whitenoiserhythm.ogg"
define sfx_wind = "audio/sfx/wind.ogg"
define sfx_switch = "audio/sfx/switch.wav"
define sfx_shotgun = "audio/sfx/182271__martian__gun-for-lui.wav"

# Интерфейс
define sfx_ui_click = "audio/sfx/switch.wav"#"audio/sfx/shelk_knock.ogg"
define sfx_ui_over = "audio/sfx/UI 03 Over.ogg"
define sfx_ui_shelk = "audio/sfx/switch.wav"

# каналы
init python:
    renpy.music.register_channel("ui", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx2", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx3", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("music2", mixer="music", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
