# Музыка
define music_main_theme = "audio/bg/Menu/Alone_in_the_space_edit.mp3"
define music_waves = "audio/bg/waves.mp3"
define music_theme_5day = "audio/bg/Theme_5day.mp3"
define music_quite_ambient = "audio/bg/Quite_ambient.mp3"
define music_quite_ambient2 = "audio/bg/Quite_ambient2.mp3"
define music_hope_ambient = "audio/bg/Hope_ambient.mp3"
define music_nervous_ambient = "audio/bg/Nervous_ambient.mp3"
define music_sad = "audio/bg/Sad.mp3"
define music_sad_post_rock = "audio/bg/Sad_post_rock.mp3"
define music_capitan_koridor = "audio/bg/Capitan_koridor.mp3"
define music_theme_cosmos = "audio/bg/CG_cosmos/Theme_cosmos.mp3"
define music_escape_room_full = "audio/bg/Escape_room/Escape_room_full.mp3"
define music_make_this_right = "audio/bg/Choices/Make_this_right.mp3"
define music_kitchen_daily = "audio/bg/Kitchen/Kitchen_daily.mp3"
define music_3day_happy_kitchen = "audio/bg/Kitchen/3day_Happy_kitchen.mp3"
define music_solar_system = "audio/bg/Main_Themes/SolarSystem.mp3"
define music_in_the_mirror = "audio/bg/Main_Themes/In_the_mirror.mp3"
define music_alone_in_the_space = "audio/bg/Main_Themes/Alone_in_the_space.mp3"
define music_daily = "audio/bg/Main_Themes/Daily.mp3"
define music_light = "audio/bg/Main_Themes/Light.mp3"
define music_untitled_5 = "audio/bg/Pod_voprosom/untitled-5_dkBjqlng.mp3"
define music_theme_bad_ending_cosmos = "audio/bg/Endings/Theme_Bad_ending_cosmos.mp3"
define music_bad_end_after_talk = "audio/bg/Endings/Bad_end_after_talk.mp3"
define music_epilogue = "audio/bg/Endings/Epilogue.mp3"
define music_action_fight = "audio/bg/Action/Fight.mp3"
define music_anxiety = "audio/bg/Anxiety/anxiety.mp3"
define music_creepy_tuc_tuc = "audio/bg/Anxiety/creepy_tuc_tuc.mp3"
define music_creepy_without_tuc_tuc = "audio/bg/Anxiety/creepy_without_tuc_tuc.mp3"
define music_perd_dolbej = "audio/bg/Anxiety/perd_dolbej.mp3"
define music_perd_quite_ambient = "audio/bg/Anxiety/perd_quite_ambient.mp3"
define music_perd_sad_ambient = "audio/bg/Anxiety/perd_sad_ambient.mp3"
define music_perd_sad_ambient2 = "audio/bg/Anxiety/perd_sad_ambient2.mp3"
define music_reflections = "audio/bg/Anxiety/reflections.mp3"
define music_Xtonicheskoe_creepy = "audio/bg/Anxiety/Xtonicheskoe_creepy.mp3"
define music_Xtonicheskoe_fon = "audio/bg/Anxiety/Xtonicheskoe_fon.mp3"
define music_Xtonicheskoe_fon_dinamika = "audio/bg/Anxiety/Xtonicheskoe_fon_dinamika+.mp3"

# Игра
define sfx_alarm1 = "audio/sfx/alarm.ogg"
define sfx_alarm2 = "audio/sfx/alarm2.ogg"
define sfx_alarm3 = "audio/sfx/alarm3.ogg"
define sfx_cup_on_table = "audio/sfx/cup_on_table.ogg"
define sfx_drama = "audio/sfx/drama.ogg"
define sfx_drama_boom = "audio/sfx/drama_boom.ogg"
define sfx_electrisity1 = "audio/sfx/electrisity.ogg"
define sfx_electrisity2 = "audio/sfx/electrisity2.ogg"
define sfx_electrisity3 = "audio/sfx/electrisity3.ogg"
define sfx_earthquake_boosted = "audio/sfx/earthquake_boosted.ogg"
define sfx_evaporating_water = "audio/sfx/evaporating_water.ogg"
define sfx_explosion = "audio/sfx/explosion.ogg"
define sfx_ballons = "audio/sfx/ballons.ogg"
define sfx_ballons2 = "audio/sfx/ballons2.ogg"
define sfx_burning_fire = "audio/sfx/burning_fire.ogg"
define sfx_click2 = "audio/sfx/click2.ogg"
define sfx_clicks = "audio/sfx/clicks.ogg"
define sfx_click_double = "audio/sfx/click_double.ogg"
define sfx_click_first = "audio/sfx/click_first.ogg"
define sfx_click_second = "audio/sfx/click_second.ogg"
define sfx_cough_man = "audio/sfx/cough_man.ogg"
define sfx_cough_man2 = "audio/sfx/cough_man2.ogg"
define sfx_cough_women = "audio/sfx/cough_women.ogg"
define sfx_crunch_whoosh = "audio/sfx/crunch_whoosh.ogg"
define sfx_door_open = "audio/sfx/door_open.ogg"
define sfx_door_creaking = "audio/sfx/door_creaking.ogg"
define sfx_light_on = "audio/sfx/light_on.ogg"
define sfx_fall_body = "audio/sfx/fall_body.ogg"
define sfx_falling_objects = "audio/sfx/falling_objects.ogg"
define sfx_fon_generator1 = "audio/sfx/fon_generator.ogg"
define sfx_fon_generator2 = "audio/sfx/fon_generator2.ogg"
define sfx_fon_stremniy = "audio/sfx/fon_stremniy.ogg"
define sfx_glitch = "audio/sfx/glitch.ogg"
define sfx_laugh_men1 = "audio/sfx/heh_men.ogg"
define sfx_laugh_men2 = "audio/sfx/heh_victor.ogg"
define sfx_laugh_people = "audio/sfx/people_laughing.ogg"
define sfx_laugh_iris1 = "audio/sfx/Iris_laught.ogg"
define sfx_laugh_iris2 = "audio/sfx/Iris_ridicule.ogg"
define sfx_laugh_female1 = "audio/sfx/laugh_female1.ogg"
define sfx_laugh_female2 = "audio/sfx/laugh_female2.ogg"
define sfx_laugh_female3 = "audio/sfx/laugh_female3.ogg"
define sfx_loop_piano = "audio/sfx/loop_piano.ogg"
define sfx_heat_metal = "audio/sfx/heat_metal.ogg"
define sfx_heart_beat_neutral = "audio/sfx/heart_beat_neutral.ogg"
define sfx_heart_beat1 = "audio/sfx/heart_beat1.ogg"
define sfx_heart_beat2 = "audio/sfx/heart_beat2.ogg"
define sfx_heart_beat_slow = "audio/sfx/heart_beat_slow.ogg"
define sfx_heart_beat_fast = "audio/sfx/heart_beat_fast.ogg"
define sfx_hiss = "audio/sfx/hiss.ogg"
define sfx_hiss_pain = "audio/sfx/hiss_pain.ogg"
define sfx_hiss_long = "audio/sfx/hiss_long.ogg"
define sfx_hiss_electrisity = "audio/sfx/hit_on_panel_dvigatel.ogg"
define sfx_hiss_with_voice1 = "audio/sfx/hiss_with_voice1.ogg"
define sfx_hit = "audio/sfx/hit.ogg"
define sfx_hit_metal = "audio/sfx/hit_metal.ogg"
define sfx_hit_sword = "audio/sfx/hit_sword.ogg"
define sfx_hit_reverb = "audio/sfx/hit_reverb.ogg"
define sfx_kitchen = "audio/sfx/kitchen.ogg"
define sfx_kitchen_table = "audio/sfx/kitchen_table.ogg"
define sfx_metal_door = "audio/sfx/metal_door.ogg"
define sfx_metal_knock = "audio/sfx/metal_knock.ogg"
define sfx_metal_skrip = "audio/sfx/metal_skrip.ogg"
define sfx_metal_hits_grinding = "audio/sfx/metal_hits_grinding.ogg"
define sfx_morse = "audio/sfx/morse.ogg"
define sfx_noise = "audio/sfx/noise.ogg"
define sfx_noise_banging = "audio/sfx/noise_banging.ogg"
define sfx_pat = "audio/sfx/pat.ogg"
define sfx_pisk_one = "audio/sfx/pisk.ogg"
define sfx_pisk = "audio/sfx/pisk.ogg"
define sfx_pisk_cicle = "audio/sfx/pisk_cicle.ogg"
define sfx_pisk_radist = "audio/sfx/pisk_radist.ogg"
define sfx_push_button = "audio/sfx/push_button.ogg"
define sfx_power_down = "audio/sfx/power_down.ogg"
define sfx_power_up = "audio/sfx/power_up.ogg"
define sfx_putting_down_plate = "audio/sfx/putting_down_plate.ogg"
define sfx_radist_hit_table = "audio/sfx/radist_hit_table.ogg"
define sfx_run_metal_floor = "audio/sfx/run_metal_floor.ogg"
define sfx_shlepok = "audio/sfx/shlepok.ogg"
define sfx_scream_women_ah = "audio/sfx/scream_women_ah.ogg"
define sfx_screaming = "audio/sfx/screaming.ogg"
define sfx_shooting = "audio/sfx/shooting.ogg"
define sfx_silent_alarm = "audio/sfx/silent_alarm.ogg"
define sfx_steps = "audio/sfx/steps.ogg"
define sfx_steps_coridor = "audio/sfx/steps_coridor.ogg"
define sfx_steps_short = "audio/sfx/steps_short.ogg"
define sfx_steps_two = "audio/sfx/steps_two.ogg"
define sfx_steps_one = "audio/sfx/steps_one.ogg"
define sfx_steps_fast = "audio/sfx/steps_fast.ogg"
define sfx_steps_fast_two = "audio/sfx/steps_fast_two.ogg"
define sfx_steps_fast_short = "audio/sfx/steps_fast_short.ogg"
define sfx_strem_steps = "audio/sfx/strem_steps.ogg"
define sfx_strem_steps_david = "audio/sfx/strem_steps_david.ogg"
define sfx_steps_slow = "audio/sfx/steps_slow.ogg"
define sfx_stun = "audio/sfx/stun.ogg"
define sfx_slurp = "audio/sfx/slurp.ogg"
define sfx_shing_sword = "audio/sfx/shing_sword.ogg"
define sfx_talk = "audio/sfx/talk.ogg"
define sfx_talk_people = "audio/sfx/talk_people.ogg"
define sfx_tik_tak = "audio/sfx/tik_tak.ogg"
define sfx_tik_tak2 = "audio/sfx/tik_tak2.ogg"
define sfx_ventel = "audio/sfx/ventel.ogg"
define sfx_ventel_noise = "audio/sfx/ventel_noise.ogg"
define sfx_ventel2 = "audio/sfx/ventel2.ogg"
define sfx_ventilation = "audio/sfx/ventilation.ogg"
define sfx_water_splash = "audio/sfx/water_splash.ogg"
define sfx_whistling = "audio/sfx/whistling.ogg"
define sfx_writing = "audio/sfx/writing.ogg"
define sfx_intro = "audio/sfx/intro.ogg"
define sfx_disclamer = "audio/sfx/disclamer.ogg"

# Мини игры
define sfx_safe_button = "audio/sfx/mini_games/safe_button.ogg"
define sfx_error2 = "audio/sfx/mini_games/error2.ogg"
define sfx_error4 = "audio/sfx/mini_games/error4.ogg"
define sfx_safe_open_lock = "audio/sfx/mini_games/safe_open_lock.ogg"
define sfx_click_pick_up = "audio/sfx/mini_games/click_pick_up.ogg"
define sfx_click_put_down = "audio/sfx/mini_games/click_put_down.ogg"
define sfx_click_deselect = "audio/sfx/mini_games/click_deselect.ogg"
define sfx_connect3 = "audio/sfx/mini_games/connect3.ogg"
define sfx_win = "audio/sfx/mini_games/win.ogg"
define sfx_disconnect = "audio/sfx/mini_games/disconnect.ogg"
define sfx_lock_moving = "audio/sfx/mini_games/lock_moving.ogg"
define sfx_lock_moving_back = "audio/sfx/mini_games/lock_moving_back.ogg"
define sfx_lock_pick_break = "audio/sfx/mini_games/lock_pick_break.ogg"
define sfx_lock_unlock = "audio/sfx/mini_games/lock_unlock.ogg"


# Интерфейс
define sfx_ui_achieve = "audio/sfx/UI 01 Achive.ogg"
define sfx_ui_click = "audio/sfx/UI 02 Click.ogg"
define sfx_ui_over = "audio/sfx/UI 03 Over.ogg"

# Puzzle defaults
define sfx_puzzle_click_rotate = sfx_ui_click
define sfx_puzzle_place = sfx_click_put_down
define sfx_puzzle_win = sfx_win

# lockpick
define SFX_UNLOCK = sfx_lock_unlock
define SFX_MOVE = sfx_lock_moving
define SFX_MOVE_BACK = sfx_lock_moving_back
define SFX_BREAK = sfx_lock_pick_break

# каналы
init python:
    renpy.music.register_channel("ui", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx2", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx3", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("music2", mixer="music", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
